/*
 * generated by Xtext
 */
package org.xtext.example.myModel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CSharpRuntimeModule extends org.xtext.example.myModel.AbstractCSharpRuntimeModule {

}
