/*
* generated by Xtext
*/
package org.xtext.example.myModel;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CSharpUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.myModel.ui.internal.CSharpActivator.getInstance().getInjector("org.xtext.example.myModel.CSharp");
	}
	
}
