/**
 * generated by Xtext
 */
package org.xtext.example.myModel.ui.contentassist;

import org.xtext.example.myModel.ui.contentassist.AbstractCSharpProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CSharpProposalProvider extends AbstractCSharpProposalProvider {
}
