/*
 * generated by Xtext
 */
package org.myModel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.myModel.ui.internal.CSharpActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CSharpExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CSharpActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CSharpActivator.getInstance().getInjector(CSharpActivator.ORG_MYMODEL_CSHARP);
	}
	
}
