/**
 * generated by Xtext
 */
package org.myModel.validation;

import org.myModel.validation.AbstractCSharpValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CSharpValidator extends AbstractCSharpValidator {
}
