/*
 * generated by Xtext
 */
package org.myModel.ui.contentassist

import org.myModel.ui.contentassist.AbstractCSharpProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CSharpProposalProvider extends AbstractCSharpProposalProvider {
}
