/*
 * generated by Xtext
 */
package org.xtext.example.myModel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CSharpUiModule extends org.xtext.example.myModel.ui.AbstractCSharpUiModule {
	public CSharpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
