/*
* generated by Xtext
*/
package org.myModel;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CSharpUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.myModel.ui.internal.CSharpActivator.getInstance().getInjector("org.myModel.CSharp");
	}
	
}
